#!/bin/bash
# ============================================================
# Zyniq Analytics — Production Server Bootstrap
# Target: Ubuntu 24 LTS (fresh install)
# Run as: sudo bash setup.sh
# ============================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC}   $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
die()     { echo -e "${RED}[ERR]${NC}  $1"; exit 1; }

[[ $EUID -ne 0 ]] && die "Please run as root: sudo bash setup.sh"

# --- Config ---
APP_DIR="/opt/zyniq-analytics"
REPO_URL="https://github.com/ZYNIQ-SOLUTIONS/openpanel-zyniq-version.git"
# Change REPO_URL to your actual repo URL before running

info "=== Zyniq Analytics Production Setup ==="
echo ""

# ─── 1. System Update ───────────────────────────────────────
info "Updating system packages..."
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -qq
apt-get install -y -qq curl git wget unzip openssl jq apt-transport-https ca-certificates gnupg lsb-release
success "System updated"

# ─── 2. Install Docker ──────────────────────────────────────
if command -v docker &>/dev/null; then
  warn "Docker already installed: $(docker --version)"
else
  info "Installing Docker Engine..."
  curl -fsSL https://get.docker.com | bash
  systemctl enable docker
  systemctl start docker
  success "Docker installed: $(docker --version)"
fi

# Docker Compose plugin check
if docker compose version &>/dev/null; then
  success "Docker Compose plugin: $(docker compose version)"
else
  info "Installing Docker Compose plugin..."
  apt-get install -y -qq docker-compose-plugin
  success "Docker Compose installed: $(docker compose version)"
fi

# ─── 3. Create App Directory ────────────────────────────────
info "Creating app directory: $APP_DIR"
mkdir -p "$APP_DIR"
cd "$APP_DIR"

# ─── 4. Clone or pull repo ──────────────────────────────────
if [ -d "$APP_DIR/.git" ]; then
  info "Repo already exists, pulling latest..."
  git pull
else
  info "Cloning repo..."
  git clone "$REPO_URL" "$APP_DIR"
fi
success "Repo ready at $APP_DIR"

# ─── 5. Generate Secrets ────────────────────────────────────
info "Generating secrets..."

POSTGRES_PASSWORD=$(openssl rand -hex 20)
CLICKHOUSE_PASSWORD=$(openssl rand -hex 20)
REDIS_PASSWORD=$(openssl rand -hex 20)
MONGO_PASSWORD=$(openssl rand -hex 20)
QDRANT_API_KEY=$(openssl rand -hex 24)
COOKIE_SECRET=$(openssl rand -hex 32)
ADMIN_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
PGADMIN_PASSWORD=$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | head -c 12)

success "Secrets generated"

# ─── 6. Write .env ─────────────────────────────────────────
ENV_FILE="$APP_DIR/deploy/.env"
info "Writing $ENV_FILE ..."

cat > "$ENV_FILE" <<EOF
# ============================================================
# Zyniq Analytics — Production Environment
# Auto-generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ============================================================

# ─── PostgreSQL ─────────────────────────────────────────────
POSTGRES_USER=openpanel
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=openpanel
DATABASE_URL=postgresql://openpanel:${POSTGRES_PASSWORD}@postgres:5432/openpanel?schema=public
DATABASE_URL_DIRECT=postgresql://openpanel:${POSTGRES_PASSWORD}@postgres:5432/openpanel

# ─── ClickHouse ─────────────────────────────────────────────
CLICKHOUSE_DB=openpanel
CLICKHOUSE_USER=analytics
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
CLICKHOUSE_URL=http://analytics:${CLICKHOUSE_PASSWORD}@clickhouse:8123/openpanel

# ─── Redis ──────────────────────────────────────────────────
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379

# ─── MongoDB ────────────────────────────────────────────────
MONGO_INITDB_ROOT_USERNAME=admin
MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
MONGO_URL=mongodb://admin:${MONGO_PASSWORD}@mongodb:27017

# ─── Qdrant ─────────────────────────────────────────────────
QDRANT_API_KEY=${QDRANT_API_KEY}

# ─── App URLs ───────────────────────────────────────────────
NEXT_PUBLIC_DASHBOARD_URL=https://admin.zyniq.cloud
NEXT_PUBLIC_API_URL=https://api.zyniq.cloud
API_PORT=3333
WORKER_PORT=9999

# ─── Analytics App Settings ─────────────────────────────────
BATCH_SIZE=5000
BATCH_INTERVAL=10000
CONCURRENCY=10

# ─── Security ───────────────────────────────────────────────
COOKIE_SECRET=${COOKIE_SECRET}

# ─── Kafka ──────────────────────────────────────────────────
KAFKA_BROKER_ID=1
KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
ZOOKEEPER_CLIENT_PORT=2181
ZOOKEEPER_TICK_TIME=2000

# ─── Dashboard Admin Credentials ────────────────────────────
# Used for: pgAdmin, Mongo Express, Redis Insight, Kafka UI
ADMIN_USERNAME=admin
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# ─── pgAdmin ────────────────────────────────────────────────
PGADMIN_DEFAULT_EMAIL=admin@zyniq.solutions
PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}

# ─── Optional — fill in later ───────────────────────────────
# RESEND_API_KEY=
# ANTHROPIC_API_KEY=
# OPENAI_API_KEY=
# GITHUB_CLIENT_ID=
# GITHUB_CLIENT_SECRET=
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
# VITE_OP_CLIENT_ID=
EOF

chmod 600 "$ENV_FILE"
success ".env written with generated secrets"

# ─── 7. Print Credentials Summary ───────────────────────────
echo ""
echo -e "${YELLOW}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${YELLOW}║               SAVE THESE CREDENTIALS SECURELY               ║${NC}"
echo -e "${YELLOW}╠══════════════════════════════════════════════════════════════╣${NC}"
echo -e "${YELLOW}║${NC} PostgreSQL Password : ${POSTGRES_PASSWORD}"
echo -e "${YELLOW}║${NC} ClickHouse Password : ${CLICKHOUSE_PASSWORD}"
echo -e "${YELLOW}║${NC} Redis Password      : ${REDIS_PASSWORD}"
echo -e "${YELLOW}║${NC} MongoDB Password    : ${MONGO_PASSWORD}"
echo -e "${YELLOW}║${NC} Qdrant API Key      : ${QDRANT_API_KEY}"
echo -e "${YELLOW}║${NC} Cookie Secret       : ${COOKIE_SECRET}"
echo -e "${YELLOW}║${NC} Admin Password      : ${ADMIN_PASSWORD}   (all DB UIs)"
echo -e "${YELLOW}║${NC} pgAdmin Password    : ${PGADMIN_PASSWORD}"
echo -e "${YELLOW}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
warn "These are also saved to: $ENV_FILE"
echo ""

# ─── 8. Generate Caddy hashed password ──────────────────────
info "Generating Caddy hashed password for Basic Auth..."
# Caddy hashes passwords with bcrypt. We'll use a pre-hashed placeholder mechanism.
# The Caddyfile reads CADDY_ADMIN_HASH from env. We hash it here.
if command -v caddy &>/dev/null; then
  CADDY_HASH=$(caddy hash-password --plaintext "${ADMIN_PASSWORD}" 2>/dev/null | tail -1)
else
  # Caddy not installed on host; write raw password, caddy container will be used differently
  # We'll store both and the Caddyfile will do runtime hashing via env
  CADDY_HASH="${ADMIN_PASSWORD}"
  warn "Caddy not on host — raw password stored. Caddy container handles auth."
fi

echo "CADDY_ADMIN_HASH=${CADDY_HASH}" >> "$ENV_FILE"
echo "CADDY_ADMIN_USER=admin" >> "$ENV_FILE"

success "Caddy auth configured"

# ─── 9. Create ClickHouse config ────────────────────────────
info "Creating ClickHouse auth config..."
mkdir -p "$APP_DIR/deploy/clickhouse/config.d"
mkdir -p "$APP_DIR/deploy/clickhouse/users.d"

cat > "$APP_DIR/deploy/clickhouse/users.d/analytics-user.xml" <<CHEOF
<clickhouse>
    <users>
        <analytics>
            <password>${CLICKHOUSE_PASSWORD}</password>
            <networks>
                <ip>::/0</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
            <allow_databases>
                <database>openpanel</database>
            </allow_databases>
        </analytics>
        <!-- Disable default user login from outside -->
        <default>
            <password></password>
            <networks>
                <ip>127.0.0.1</ip>
                <ip>::1</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
        </default>
    </users>
</clickhouse>
CHEOF
success "ClickHouse user config written"

# ─── 10. Start Infrastructure ───────────────────────────────
info "Starting infrastructure services (databases + proxies)..."
cd "$APP_DIR/deploy"
docker compose -f docker-compose.infra.yml --env-file .env up -d

info "Waiting 20s for databases to initialize..."
sleep 20

# ─── 11. Health Checks ──────────────────────────────────────
info "Checking service health..."
FAILED=0

check_service() {
  local name="$1"
  if docker compose -f docker-compose.infra.yml --env-file .env ps --status running | grep -q "$name"; then
    success "$name is running"
  else
    warn "$name may not be healthy — check: docker compose -f deploy/docker-compose.infra.yml ps"
    FAILED=1
  fi
}

check_service "postgres"
check_service "clickhouse"
check_service "redis"
check_service "mongodb"
check_service "qdrant"
check_service "kafka"
check_service "caddy"

echo ""
if [[ $FAILED -eq 0 ]]; then
  success "All infrastructure services running!"
else
  warn "Some services may need attention — check logs with:"
  warn "  docker compose -f $APP_DIR/deploy/docker-compose.infra.yml logs"
fi

echo ""
info "=== Next Steps ==="
echo "  1. Point DNS records for all subdomains to this server's IP"
echo "  2. Build and start the Zyniq Analytics app:"
echo "     cd $APP_DIR/deploy && docker compose -f docker-compose.app.yml --env-file .env up -d --build"
echo "  3. Run database migrations:"
echo "     docker exec analytics-api node dist/migrate.js"
echo "  4. Visit https://admin.zyniq.cloud"
echo ""
success "Setup complete!"
